### PR TITLE
Fix buggy setting of tau PV refitting module

### PR DESCRIPTION
**Pull request by mbluj**
As name of the PR says
1. Buggy setting in the tau PV refitting module configuration corrected: Algorithm = 1 => 0
    This switches between PV=vertex[0] (Algorithm=1) to PV given by tau vertex association, i.e. closest in dz to leading track of seeding jet (Algorithm=0). 
2. Small modification on code of the PFTauPrimaryVertexProducer avoiding unnecessary multiple calls of the setEvent method of tau VertexAssociator.

Change of algorithm (to 0) causes that reference vertex used to compute tau impact parameters and their significances is correct for taus not pointing to vertex[0] (10-15% of taus from Z, mostly at low-Pt) and in consequence the impact parameters with significances are reasonable, while with Algorithm=1 significanies as big as O(1000) are observed. The change of algorithm modifies a bit distribution of MVAIsoRAW, but does not change its performance (especially for taus close to PV which are not affected by definition) 

Note: I am investigating further changes in the tau vertex definition which will be potentially subjects of new PRs. But they should probably go to another branch for simpler integration to official CMSSW.

### CODE REVIEW

**Comment by mbluj** [comment]
P.S. The new configuration of the PFTauPrimaryVertexProducer module ideally requires a new MVAIso training, but it is anyway expected for Phase-1 with some production release from 90X series.

**Comment by roger-wolf** [comment]
Hi Michal,

this one is already problematic if it potentially changes the performance it adds another quality to the PR that will be related to this branch. I'm tempted to open a new branch for these kinds of developments and to send off the this special PR as it is. In this sence I'd reject htis PR and set up a new branch for you to reopne the PR in a few minutes. Ok for you?

Cheers,
Roger

**Comment by mbluj** [comment]
Yes, it is OK.

**Comment by mbluj** [comment]
Closed. Is it fine that the new PR will be on top of previous changes?

**Comment by roger-wolf** [comment]
Yes I think that's OK.

**Pull request closed without merging**
