### PR TITLE
Address additional RECO review comments

### PR DESCRIPTION
**Pull request by steggema**
The main changes are
- simplify configuration setup
- unify charged hadron from track and charged hadron from lost track plugins (using templates)

@roger-wolf you may want to double-check the test with the updated configuration

@mbluj I noticed something odd in that the "setChargedHadronP4" method in RecoTauTag/RecoTau/interface/pfRecoTauChargedHadronAuxFunctions.h requires that a reco::Track* can be returned from the lost track (assert otherwise), however, I haven't found any such protection in the previous implementation. Have you encountered this?

### CODE REVIEW

**Comment by mbluj** [comment]
@steggema No, I have not encountered such a problem with an assert due to a lostTrack w/o a pseudoTrack, i.e. w/o track details. However, I am using 10_1_0_pre1 MiniAODs as an input where, at least in my understanding, all lost tracks have this information (by construction?). But, it could be that something changed in newer releases such that thresholds to store a lostTrack and to store its details diverged what triggers the assert.

**Comment by steggema** [comment]
@mbluj Thanks. I would understand the code
https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/PatAlgos/python/slimming/lostTracks_cfi.py#L17
https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/PatAlgos/plugins/PATLostTracks.cc#L222
such that all high-purity tracks auto-pass, regardless of pT, 
but that track properties are only saved for pT > 0.95 GeV
https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/PatAlgos/plugins/PATLostTracks.cc#L245
So I'm not sure why we didn't see this popping up before.
It could make even more sense to change https://github.com/cms-sw/cmssw/blob/09c3fce6626f70fd04223e7dacebf0b485f73f54/RecoTauTag/RecoTau/src/pfRecoTauChargedHadronAuxFunctions.cc#L28 such that the p4 is taken from the Candidate if no track is found, however, it would also mean that we auto-pass the (negligibly loose?) track selection criteria.

**Comment by mbluj** [comment]
On Wed, Apr 18, 2018 at 4:02 PM, Jan Steggemann <notifications@github.com>
wrote:

> @mbluj <https://github.com/mbluj> Thanks. I would understand the code
> https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/PatAlgos/python/
> slimming/lostTracks_cfi.py#L17
> https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/PatAlgos/plugins/
> PATLostTracks.cc#L222
> such that all high-purity tracks auto-pass, regardless of pT,
> but that track properties are only saved for pT > 0.95 GeV
> https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/PatAlgos/plugins/
> PATLostTracks.cc#L245
>
Yes, you are right.

>
> So I'm not sure why we didn't see this popping up before.
>
I do not know. Maybe. high-purity tracks with pT<0.95GeV not used by PFlow
are very rare with 2018 detector I used?

> It could make even more sense to change https://github.com/cms-sw/
> cmssw/blob/09c3fce6626f70fd04223e7dacebf0b485f73f54/RecoTauTag/RecoTau/
> src/pfRecoTauChargedHadronAuxFunctions.cc#L28 such that the p4 is taken
> from the Candidate if no track is found, however, it would also mean that
> we auto-pass the (negligibly loose?) track selection criteria.
>
Yes, it makes sense to me to build the guys from candidate only if track
details are not stored (which we know about that it is high-purity track
and has Pt>0.5GeV as it is minimal PFTau requirement). However, I expect
that the difference with allowing and discarding such guys will be marginal.

**Comment by steggema** [comment]
OK, I did so. @roger-wolf This is fine to merge from my side, and it may make sense to do so now, and rather produce the comparisons in parallel/after (the reduced matrix tests as well as the tau@MiniAOD reco run fine) since we also haven't done that yet for the previous larger chunk.

**Comment by mbluj** [comment]
Thanks Jan. 
I'm not working on anything related to taus on top of miniAOD and I'm also fine with merging with the main branch.
I think I will be able to perform my tests (if needed) on Friday afternoon.

**Pull request merged**
