### PR TITLE
Added possibility to recompute tau isolation on miniAOD and PAT

### PR DESCRIPTION
**Pull request by anehrkor**
The main additions are RecoTauTag/RecoTau/interface/RecoTauDiscriminationByIsolationT.h (template class of PFRecoTauDiscriminationByIsolation.cc) and PhysicsTools/PatAlgos/plugins/PATTauIDEmbedder.cc

### CODE REVIEW

**Comment by jpavel** [comment]
Hi Alex, thanks for the PR - can you provide an example workflow how to use your additions? @andrewj314 can you check that this PR integrates smoothly and runs according to Alex's documentation?

**Comment by anehrkor** [comment]
This addition introduces the possibility to recompute the tau isolation almost independent of the dataformat (e.g., AOD or PAT). The main tool is the class RecoTauTag/RecoTau/interface/RecoTauDiscriminationByIsolationT.h which is a template of RecoTauTag/RecoTau/plugins/PFRecoTauDiscriminationByIsolation.cc.

**Implementations of this class for AOD:**

RecoTauTag/RecoTau/plugins/PFTauDiscriminationByIsolation.cc
RecoTauTag/RecoTau/python/PFTauDiscriminationByIsolation_cfi.py

**Implementations of this class for PAT/miniAOD:**

PhysicsTools/PatAlgos/plugins/PATTauDiscriminationByIsolation.cc
PhysicsTools/PatAlgos/plugins/PATSlimmedTauDiscriminationByIsolation.cc
PhysicsTools/PatAlgos/python/PATTauDiscriminationByIsolation_cfi.py
PhysicsTools/PatAlgos/python/PATSlimmedTauDiscriminationByIsolation_cfi.py

**How to recalculate the isolation and store it in the output tau collection:**

Write a python config file as you normally would. As input you can use a normal AOD file, a PAT tuple and of course a miniAOD file. They should of course all be in edm format. Now any discriminator that you want to recalculate you can simply clone from RecoTauTag/Configuration/HPSPFTaus_cff.py like so:

``` python
process.load(‘RecoTauTag.Configuration.HPSPFTaus_cff.py‘)
process.exampleIso = hpsPFTauMVA3IsolationChargedIsoPtSum.clone()
…
process.p = cms.Path(…*process.exampleIso*…)
```

In case of miniAOD input, you need to also change some collections to be used. This is dependent on what discriminator you want to rerun and needs to be checked and corrected for by yourself. Basically when cloning, you need to replace any collection with its slimmed counterpart (e.g., `vertexSrc = cms.InputTag(“offlinePrimaryVertices“)` -> `vertexSrc = cms.InputTag(“offlineSlimmedPrimaryVertices“)`).

In case of PAT and miniAOD input, the class PhysicsTools/PatAlgos/plugins/PATTauIDEmbedder.cc is needed to embed the new/recalculated isolation in the output pat::Tau. In your config file you will need to add something like the following:

``` python
embedID = cms.EDProducer(“PATTauIDEmbedder“,
                src = cms.InputTag(‘slimmedTaus‘), # input tau collection to be used
                tauIDSources = cms.PSet( # put all recalculated discriminators here
                                   recalculatedExampleIso = cms.InputTag(‚examplesIso‘),
                                   ),
                )
setattr(process,“newTauCollection“,embedID), # newTauCollection will be the name of the output collection

#process.p needs to have an addition AFTER all discriminators you chose to redo are calculated:
process.p = cms.Path(…*process.exampleIso*getattr(process,“newTauCollection“)*…)
```

Remaining issues:
Track information for charged tracks below 950 MeV and most neutral particles (bug?) is missing in miniAOD. Therefore, validation of code only possible on AOD and „normal“ PAT.

**Comment by andrewj314** [comment]
@anehrkor could you provide sample AOD and MiniAOD files for testing purposes?

**Comment by anehrkor** [comment]
I used a DYJetsToLL madgraph Phys14 sample (or rather one of the samples' files) to produce a miniAOD file. I uploaded the AOD file and the config file used to create a miniAOD file to lxplus (/afs/cern.ch/user/a/anehrkor/public).

**Comment by andrewj314** [comment]
I'm running into some issues following this workflow - the line:

process.exampleIso = hpsPFTauMVA3IsolationChargedIsoPtSum.clone()

Crashes cmsRun with the exception:

Exception Message:

python encountered the error: <type 'exceptions.NameError'>

name 'hpsPFTauMVA3IsolationChargedIsoPtSum' is not defined

Even though the relevant code is there and HPSPFTaus_cff appears to load
properly. Is there anything I'm missing here? I attached my config file.

Thanks!

**Comment by anehrkor** [comment]
That's weird. I'm no expert when it comes to python configuration, however. Maybe try something like `from RecoTauTag.Configuration.HPSPFTaus_cff import *` (or just hpsPFTauMVA3IsolationChargedIsoPtSum) ?

**Comment by andrewj314** [comment]
That was the issue - needed that import statement at the top. Otherwise appears to work as long as appropriate prescription for AOD/MiniAOD is applied. Merging.

**Pull request merged**
