### PR TITLE
Update to new Tau Id MVA training performed on Summer16 samples

### PR DESCRIPTION
**Pull request by anehrkor**
This PR includes the changes needed in order to access the new tau Id training performed with Summer16 MC.

There are some minor other changes like replacing spaces by tabs and the addition of a globally accessible test file such that the testing code can be run out of the box.

Cheers,
Alex

### CODE REVIEW

**Comment by roger-wolf** [comment]
Hi Alex, 
thanx a lot! I'll merge and test this PR asa I get to it. Is it that the names you are using for MVA products/payloads will turn official including these tags "2016" added to all names? 

@mbluj @isobelojalvo 
Related to this (and not directly addressed to Alex, but as a general question to all) would it make sense at some point in time either to clean up all old ID's which might never be used again or to arrive at a common naming scheme? What do people think. 

On the unit test -- for this branch it looks fine to me. I'm happy if I can test your developments easily. But for the upload to official-cmssw the changes look too temporary to me to include this file. E.g. they point to a file that we rely on to be available for a long time, or replaced accordingly. I'll keep the original rerunMVAIsolationOnMiniAOD test structure for the time being to have something that upon rerunning tauID will always work and produce something. Do you think Alex that it makes sense to bring the test files you initially commited to a more "fundamental/basic" level so that it could be part of a common unit test workflow. Your Aachen validation colleagues could maybe make an effort in this direction in coordination with you?

Cheers,
Roger

**Comment by isobelojalvo** [comment]
@roger-wolf I fully endorse the cleanup of old trainings and arriving at a common, simplified naming scheme. I am even happy to buy a beer or coffee for the person who does that. :)

**Comment by veelken** [comment]
Hi,

I would volunteer to do the clean-up (also of all old tau ID code that isn’t used anymore) in case you can grant EPR credit for the clean-up work.

Cheers,


Christian

**Comment by roger-wolf** [comment]
Great!

Christian might be one of the best persons to do this, no?

Cheers,
Roger

**Comment by anehrkor** [comment]
Hi Roger,

the names used for the MVA trainings are sort of final/official since they have been uploaded to the production DB (FrontierProd) already. One could of course change them, recompile the sqlite file and then ask Arun to upload the new ones but I think the cost/reward ratio is not so great to be honest :)
I also personally think that adding the year to the name is not so bad since this will make the training somewhat more identifiable later on. Especially since there will likely be another training for 2017 samples...

About the unit-tests: to me `rerunMVAIsolationOnMiniAOD` is more of an example class which we can point to in a TWiki to show people how to apply new tau Id's during their ntuple production.
I suppose it makes sense to provide some more basic testing class but I do not plan to pursue this. It might indeed be something for the people doing validation work. I think it's best to talk to them directly though.

Cheers,
Alex

**Comment by mbluj** [comment]
Yes, I agree Christian will be best person to do the cleanup. I think, we can grant EPRs for this (+beer from Isobel :) - details to be discussed offline (scope of the work and related EPRs, timeline and convention, etc.)
@anehrkor There are two types of names: DB-tags which are already set and I will not change them and names of discriminants which still can be defined (for a legacy rereco, 2017, etc.)

**Pull request merged**
