### PR TITLE
Add switch in L1 matcher to produce full PFtaus

### PR DESCRIPTION
**Pull request by lwezenbe**
This PR is a result of the discussion in [PR#151](https://github.com/cms-tau-pog/cmssw/pull/151) where it was concluded to change the L1 matcher to be able to produce a collection of the original taus to use as input for the DeepTauProducer.
Two switches were added, one to add "full" taus to the collection and one to change the vertex of the tau in the way it was originally done.
**Testing**
The regular tests as mentioned on [this page](http://cms-sw.github.io/PRWorkflow.html) were performed and succeeded

### CODE REVIEW

**Comment by swozniewski** [comment]
Hi @lwezenbe, I did not run anything so far but looking through the changes I'm wondering about the types: You are replacing a PFTauCollection (which is defined as a vector of PFTaus) by a RefVector of PFTauCollection, which is a vector of vectors. Won't we rather need a RefVector of PFTaus?

**Comment by lwezenbe** [comment]
Yes, that was also my initial thought when adapting the code, but defining this RefVector with reco::PFTau gives the errors:
`error: no type named 'value_type' in 'class reco::PFTau'`

and

`/afs/cern.ch/work/l/lwezenbe/TauPOG/cmssw_dev/RefVectorL1Matcher/CMSSW_12_0_0_pre5/src/RecoTauTag/HLTProducers/src/L1THLTTauMatching.cc:26:30: error: template argument 2 is invalid
   26 |   unique_ptr<RefVector<reco::PFTau>> tauL2jets(new RefVector<reco::PFTau>);`

I must admit that I am still not fully comfortable with the ins and outs of RefVectors so I'll drop my definition of the collection below just in case I have wrongly made the change:
`  unique_ptr<RefVector<reco::PFTau>> tauL2jets(new RefVector<reco::PFTau>);`

In any case, the issue is not really with the L1matcher, it passes through DeepTauId wonderfully, but the issue is with parsing the containers that were made with the producer, which only have a fraction of the original tau collection, through the filter afterwards.

**Comment by swozniewski** [comment]
Looks like the reference objects indeed take collections of what they refer to as template parameter. Ok, in that case I don't see what's wrong with your changes.
In order to verify my setup. With this PR and your commands I received the following error:
```
----- Begin Fatal Exception 13-Sep-2021 16:27:46 CEST-----------------------
An exception of category 'InvalidReference' occurred while
   [0] Processing  Event run: 1 lumi: 3 event: 2002 stream: 0
   [1] Running path 'HLT_DoubleMediumChargedIsoPFTauHPS35_Trk1_eta2p1_Reg_v4'
   [2] Calling method for module PFTauSelector/'hltHpsSelectedPFTausTrackPt1DeepTau35IsolationReg'
Exception Message:
ValueMap: no associated value for given product and index
----- End Fatal Exception -------------------------------------------------
```
It's not quite what was reported in the initial PR but maybe sth changed since then. Do you get the same error at the current stage?

**Comment by lwezenbe** [comment]
Yes, I do get the same error in the current stage. I believe this is due to the src for the filter module still being the larger tau collection while the DeepTau module outputs containers containing only information on the taus in its input RefVector and the filter is trying to access information from the remaining taus. When I switch the input by adding a 
`src = hltHpsL1JetsHLTDoublePFTauTrackPt1MediumChargedIsolationMatchReg`
here:
https://github.com/lwezenbe/cmssw/blob/CMSSW_12_0_X_RefVectorL1Matcherv2/RecoTauTag/HLTProducers/python/deepTauAtHLT.py#L182

the error switcher to a productNotFound error:
```
----- Begin Fatal Exception 13-Sep-2021 14:24:33 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 1 lumi: 3 event: 2002 stream: 0
   [1] Running path 'HLT_DoubleMediumChargedIsoPFTauHPS35_Trk1_eta2p1_Reg_v4'
   [2] Calling method for module PFTauSelector/'hltHpsSelectedPFTausTrackPt1DeepTau35IsolationReg'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: std::vector<reco::PFTau>
Looking for module label: hltHpsL1JetsHLTDoublePFTauTrackPt1MediumChargedIsolationMatchReg
Looking for productInstanceName: 

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
```

**Comment by swozniewski** [comment]
I hope I got the right overview of definitions of the involved modules. Just for the record, I think some definitions are found in https://raw.githubusercontent.com/cms-sw/cmssw/master/HLTrigger/Configuration/python/HLT_FULL_cff.py which is not indexed by the github search due to the large size.
Switching the source to hltHpsL1JetsHLTDoublePFTauTrackPt1MediumChargedIsolationMatchReg sounds reasonable to me. Do I see correctly that this contains the RefVector introduced in this PR and the error means that we can't simply use the references instead of PFTaus as input?

**Comment by lwezenbe** [comment]
Sorry, I somehow missed your message. But indeed, because the PFTauSelector uses [ObjectSelector](https://github.com/cms-sw/cmssw/blob/master/CommonTools/UtilAlgos/interface/ObjectSelector.h), if you want to enter a RefVector collection as the source in the PFTauSelector, you need to change the typedef of [container](https://github.com/cms-sw/cmssw/blob/master/RecoTauTag/RecoTau/plugins/PFTauSelectorDefinition.h#L23) to a RefToBase in case you want to use an edm::View to read the RefVector or as a RefVector.
And either of these two as the output collection, since the type of the output seems to be bound to selected_, will not work for any following module that tries to process it.
For the modules I have encountered, they all seemed to be [HLT1PFTau](https://github.com/cms-sw/cmssw/blob/6d2f66057131baacc2fcbdd203588c41c885b42c/HLTrigger/HLTfilters/plugins/plugins.cc#L60) which binds it (as also seen [https://github.com/cms-sw/cmssw/blob/master/HLTrigger/HLTfilters/plugins/HLTSinglet.h#L37](here) to a particle collection input and does not allow for RefVector and this is where I am currently stuck. 

Currently I am seeing two ways, but you might be able to find more elegant solution.
1) We make a copy of this general CMSSW code to work with RefToBase input
2) We make a simple cut and count filter ourselves to be used here

**Comment by lwezenbe** [comment]
Another solution I am seeing is to not stick to RefVectors, but to just make a new PFTauCollection in the L1matcher.
Instead of pushing back the Ref to myJet [here](https://github.com/cms-tau-pog/cmssw/blob/baa7d1481ec9f1a4940ddab3c6346844139f47b4/RecoTauTag/HLTProducers/src/L1THLTTauMatching.cc#L54), we could simply push back myJet to a new PFTauCollection.
Then we would simply have to run the L1 matcher before the [basicDiscriminator modules](https://github.com/cms-tau-pog/cmssw/blob/baa7d1481ec9f1a4940ddab3c6346844139f47b4/RecoTauTag/HLTProducers/python/deepTauAtHLT.py#L171-L172) and adapt their input to the output from the L1 matcher.
I have just tested this and it seemed to work fine but I might be missing the reason why we cant simply use myJet here.
One issue that would still need to be solved with this approach is the presence of [this discriminator](https://github.com/cms-tau-pog/cmssw/blob/baa7d1481ec9f1a4940ddab3c6346844139f47b4/RecoTauTag/HLTProducers/python/deepTauAtHLT.py#L171-L172), which uses the base collection used as input for the L1 matcher. But I believe this shouldnt be too hard to accomodate and this approach in general might be less intrusive than what was suggested by myself on friday

**Comment by swozniewski** [comment]
So, if we do not want to adapt all subsequent modules such that they can process refs, we need to create a PFTauCollection at some point, right? And if we need to create one, it's maybe not worth to use refs first and resolve the refs at some point. We would rather create the PFTauCollection in the Matcher already.
Effectively we would change the way the vertex is defined for the output taus of the matcher in order to be usable by the DeepTauProducer, right?

**Comment by lwezenbe** [comment]
This is also how I see it, yes, although currently I am not sure in what way the vertex should be defined yet.

**Comment by swozniewski** [comment]
This isn't clear to me neither. On the other hand, the vertex information retrieved from the leading charged cand was lost in case of using a reference, too.
@mbluj @kandrosov what's your opinion on this?

**Comment by mbluj** [comment]
Indeed, tau sequences at HLT base on selectors which produce new collections of taus passing given selection. It is different than for muons and electrons where HLT deal with references. I think we should continue our way unless there is a strong request to switch to references. The switch will require some changes in tau code. I think discussion on the switch can be interesting as it will potentially save some memory, but it is beyond the scope of this PR.

Concerning setting vertex and then applying the dz cut: as far as I remember tau.vertex method normally returns vertex associated to tau, i.e. PV closest in dz to its leading track. At HLT it is usually pixelVertex[0] as usually only this vertex is used for track seeding so tracks are associated to it (at least it was the case during run-1 and 2). This makes dz cut almost 100% effective independently on an actual cut value as by construction dz=0 in most cases. It is why a trick was made to replace tau vertex by its leading track vertex which is PCA of the track, as far as I remember. This makes dz cut sensible, however it is still very efficient not only for signal by also for fakes. So see two possibilities:
* do not change definition of tau.vertex and remove dz cut as not very useful;
* globally change definition of the tau.vertex in its producer and check if it causes any issues in offline workflows (probably not, as it probably is not used at all).

Each of options requires some studies.

**Comment by swozniewski** [comment]
Maybe I misunderstand those two options or don't have the full picture in mind. But can't we be conservative by creating a copy here https://github.com/cms-tau-pog/cmssw/pull/152/files#diff-a688b6b0836d3da24db23396fecabacb6d27cf2307365605e5fb31f3f4d6ebbdR50-R55 and setting the vertex like currently done for the simplified tau? (I think that's what @mbluj suggested once in the discussion of the initial PR). This would only fill the dummy information of the (previously) simplified taus, such that subsequent modules do not change in their performance but deepTau should also be runnable (?).

**Comment by mbluj** [comment]
> Maybe I misunderstand those two options or don't have the full picture in mind. But can't we be conservative by creating a copy here https://github.com/cms-tau-pog/cmssw/pull/152/files#diff-a688b6b0836d3da24db23396fecabacb6d27cf2307365605e5fb31f3f4d6ebbdR50-R55 and setting the vertex like currently done for the simplified tau? (I think that's what @mbluj suggested once in the discussion of the initial PR). This would only fill the dummy information of the (previously) simplified taus, such that subsequent modules do not change in their performance but deepTau should also be runnable (?).

Do you mean to copy taus and then reset their vertex instead of building new trivial ones with p4 and vertex only, right? Indeed, it might be a good solution assuming that it is clear that vertex in final collection is different than in the parent collection. It can be confusing. In fact current version is confusing too, but as tau's data are not filled it is easier to notice that there is a difference. After said this - we can go with this solution, but maybe it makes sense to check in parallel if redefining tau vertex globally, i.e. in the initial producer, will not be sensible.

**Comment by lwezenbe** [comment]
Since it seems that the vertex is only an issue for the DZ filter, I think we can actually have it both ways. For now I added an additional input tag that decides to have the original taus copied as they are without different vertex or to make an output collection of simplified taus as it was originally. The reason I did it like this is because if I understand correctly the vertex is just an issue for the DZ filter, but we would need the L1 matcher in two places. One is before the DeepTau module, which will need to use a big OR of all L1 filters if we want to share it among all paths. The idea is then to have the L1 module in the same way as before at the end right before the DZ filter to filter on the specific L1 filter match of interest to the trigger. Here I think it would be fine to just run with the simplified taus as it was before. 

If you agree with this reasoning, I will remove the commented line to set the vertex information [here](https://github.com/lwezenbe/cmssw/blob/26b4bd2ad02a3e42456fdc9e823070a79ba783db/RecoTauTag/HLTProducers/src/L1THLTTauMatching.cc#L58) and we can proceed with this. Otherwise it is very easy for me to change this to clone the original taus with the vertex information manually set as it would be with the commented line so I can remove the simplified tau altogether if you prefer.

I already ran tests for both cases and the results seemed reasonable, although I havent had time to study the output in depth yet.

**Comment by mbluj** [comment]
This solution makes sense for me, thank you.
Just for a discussion (I have not a strong opinion):
* maybe one can invent more precise name for the switch than `simplifiedTau` as taus are not simplified (as physics object), but their content cleared;
* does it make sense to decouple simplification/clearing from the redefinition of its vertex?

**Comment by lwezenbe** [comment]
> maybe one can invent more precise name for the switch than simplifiedTau as taus are not simplified (as physics object), but their content cleared;

This name was actually just the first thing that came to mind, but it could be made more clear like "reduceTauContent" or "clearTauContent"

> does it make sense to decouple simplification/clearing from the redefinition of its vertex?

Do you mean here that you do not think it makes sense that line [49-51](https://github.com/cms-tau-pog/cmssw/blob/26b4bd2ad02a3e42456fdc9e823070a79ba783db/RecoTauTag/HLTProducers/src/L1THLTTauMatching.cc#L49-L51) are separated from the place where the new "simplified" tau object is defined or that you would think it might make sense to try to decouple even more? In the first case I think we can move these things together since we will not need the new vertex information in the case where the simplifiedTau option is set to False. Or maybe I am misunderstanding your intention here.

**Comment by mbluj** [comment]
> > maybe one can invent more precise name for the switch than simplifiedTau as taus are not simplified (as physics object), but their content cleared;
> 
> This name was actually just the first thing that came to mind, but it could be made more clear like "reduceTauContent" or "clearTauContent"

I vote for "reduceTauContent".

> > does it make sense to decouple simplification/clearing from the redefinition of its vertex?
> 
> Do you mean here that you do not think it makes sense that line [49-51](https://github.com/cms-tau-pog/cmssw/blob/26b4bd2ad02a3e42456fdc9e823070a79ba783db/RecoTauTag/HLTProducers/src/L1THLTTauMatching.cc#L49-L51) are separated from the place where the new "simplified" tau object is defined or that you would think it might make sense to try to decouple even more? In the first case I think we can move these things together since we will not need the new vertex information in the case where the simplifiedTau option is set to False. Or maybe I am misunderstanding your intention here.

I mean that in principle one could also like to produce "full" PFTau with a new vertex or "cleared" PFTau with original vertex (the latter sounds less probable), which will require two switches. But, maybe it is just an academic problem which complicates setup without real use-cases? What do you think?

**Comment by lwezenbe** [comment]
I cant immediately think of real use-cases for this, but as it should be fairly straightforward to implement, I think we can include it in case we change our mind at some point.

**Comment by lwezenbe** [comment]
Hello @mbluj, I believe this PR should be ready for merging and propagation to the central cmssw. I have already changed the title and description. Could you take a look? We are aiming to make it in CMSSW_12_1_0.

**Comment by mbluj** [comment]
Yes, it is fine, thank you!
I will merge it and prepare PR to master (12_1_X).
Have you already run all normal tests?

**Comment by mbluj** [comment]
BTW, this PR does change not only L1 matcher, but also configuration in `RecoTauTag/HLTProducers/python/deepTauAtHLT.py`. Is it OK? Will it work w/o introducing changes in different places, e.g. in the deepTau producer? Maybe it makes sense to not mix things in this branch? If you agree, please update this development limiting changes in the `RecoTauTag/HLTProducers/python/deepTauAtHLT.py` to what is needed for the L1 matcher, while the rest will be added in the main deeptau PR. Do you agree?
I will revert merging this PR and then merge again when this issue is understood.

**Comment by mbluj** [comment]
Small correction: I do not revert. Instead of it, I would like you to prepare a small PR removing unnecessary changes in `RecoTauTag/HLTProducers/python/deepTauAtHLT.py`. Fine with you?

**Comment by lwezenbe** [comment]
That's fine for me. In principle this file gets removed in the other open PR and replaced with two customisation function files for 2 different working points. So I was going to manually follow up if it actually is properly removed there after the changes from this PR are included in the base in which that PR should be merged. If you prefer I can make a separate PR however.

**Comment by mbluj** [comment]
Thanks for confirmation that the changes are not needed. I will remove the changes myself and commit directly to the branch (w/o a PR) and then PR to official CMSSW.

**Comment by mbluj** [comment]
> That's fine for me. In principle this file gets removed in the other open PR and replaced with two customisation function files for 2 different working points. So I was going to manually follow up if it actually is properly removed there after the changes from this PR are included in the base in which that PR should be merged. If you prefer I can make a separate PR however.

Now after I checked other PR (#151) it is clear for me that nothing needs be changed here. Please solve conflict in #151 caused by merging this PR and check my other comments. If there are anything more pending I would like to merge #151 before this weekend to start integration with the official CMSSW.

**Pull request merged**
