### PR TITLE
new datatype for reco pf tau discriminators

### PR DESCRIPTION
**Pull request by swozniewski**
A new datatype PFTauDiscriminatorContainer is introduced in order to store raw value and bools for working points in a single object and to reduce the number of PFTauDiscriminators this way. This affects all discriminators that are multiplexed by the RecoTauDiscriminantCutMultiplexer. Before, it ran once per working point and created a PFTauDiscriminator each. Now, it runs once, saves the raw value and WP bools in a PFTauDiscriminatorContainer. The PATTauProducer is adapted accordingly: Untouched PFTauDiscriminators are processed as before. PFTauDiscriminatorContainers are processed once writing out all requested quantities.
A test sample of 100 evts has been processed through the RECO and the PAT step, with and without these changes. The distributions of all tau discriminator quantities were identical.
Running the matrix tests, no additional errors caused by these changes have been detected.

### CODE REVIEW

**Comment by mbluj** [comment]
Hi Sebastian,

thank you for this long awaited development! I have a few question to it before I will be able to inspect related code changes (probably next week):
* Can the code be used for all types of discriminants, i.e. MVAIso, anti-e MVA and cut-based iso? All of them have raw values and sets of WPs defined by cuts on the raw values,
* Can the new code be used with pat::Tau-based discriminants meant to re-run MVA tau-Ids on top of MiniAOD?

**Comment by swozniewski** [comment]
Hi @mbluj ,

- in priciple, the new dataformat could be used for all discriminators. It's just saving a struct of a double and a std::vector<bool> where the previous format had a double. Currently I've applied it only in the RecoTauDiscriminantCutMultiplexer, which processes the MVAIsos and anti-e MVA. The remaining discriminators are created without or with just a few working points. So there I thought to better stay with the old and simpler format for now. But that is up for discussion.
I'd also like to point to the 'category' that is written out for anti-e MVA. As it currently is the only case where this variable exists, I didn't include it in the new format. It's still written out as a PFTauDiscriminator. Could be changed if preferred.
- The format of PAT::Taus is not changed. The PAT-Tau-Producer can read the new format and creates the same PAT::Taus as before. There should be no changes for rerunning IDs on miniAOD.

**Comment by mbluj** [comment]
>
>    - in priciple, the new dataformat could be used for all
>    discriminators. It's just saving a struct of a double and a std::vector
>    where the previous format had a double. Currently I've applied it only in
>    the RecoTauDiscriminantCutMultiplexer, which processes the MVAIsos and
>    anti-e MVA. The remaining discriminators are created without or with just a
>    few working points. So there I thought to better stay with the old and
>    simpler format for now. But that is up for discussion.
>
I think it is sensible to do so, as module for cut-based isolation is also
executed several times just for different WPs and different ingredients of
combined isolation (charged, neutral, PU, and combined pT-sums). However,
it can be done in other PR - to be discussed.

>
>    - I'd also like to point to the 'category' that is written out for
>    anti-e MVA. As it currently is the only case where this variable exists, I
>    didn't include it in the new format. It's still written out as a
>    PFTauDiscriminator. Could be changed if preferred.
>
It is as IsoMVA has not event categories in the sense as anti-e MVA has,
e.g. depending if tau matches or not to reco electron. I think it makes
sense to produce category as other "discriminants" are produced even if it
is not a discriminat per se.

>
>    - The format of PAT::Taus is not changed. The PAT-Tau-Producer can
>    read the new format and creates the same PAT::Taus as before. There should
>    be no changes for rerunning IDs on miniAOD.
>
I meant tau discriminators run on top on pat::Taus, namely
RecoTauTag/RecoTau/plugins/PPATTauDiscriminantCutMultiplexer.cc,
ATTauDiscriminationByMVAIsolationRun2.cc,
PATTauDiscriminationAgainstElectronMVA6.cc

**Comment by swozniewski** [comment]
Am 31.08.2018 um 14:25 schrieb mbluj:
> >
> > - in priciple, the new dataformat could be used for all
> > discriminators. It's just saving a struct of a double and a std::vector
> > where the previous format had a double. Currently I've applied it 
> only in
> > the RecoTauDiscriminantCutMultiplexer, which processes the MVAIsos and
> > anti-e MVA. The remaining discriminators are created without or with 
> just a
> > few working points. So there I thought to better stay with the old and
> > simpler format for now. But that is up for discussion.
> >
> > I think it is sensible to do so, as module for cut-based isolation 
> is also
> executed several times just for different WPs and different ingredients of
> combined isolation (charged, neutral, PU, and combined pT-sums). However,
> it can be done in other PR - to be discussed.
>
> >
> > - I'd also like to point to the 'category' that is written out for
> > anti-e MVA. As it currently is the only case where this variable 
> exists, I
> > didn't include it in the new format. It's still written out as a
> > PFTauDiscriminator. Could be changed if preferred.
> >
> > It is as IsoMVA has not event categories in the sense as anti-e MVA has,
> e.g. depending if tau matches or not to reco electron. I think it makes
> sense to produce category as other "discriminants" are produced even if it
> is not a discriminat per se.
>
> >
> > - The format of PAT::Taus is not changed. The PAT-Tau-Producer can
> > read the new format and creates the same PAT::Taus as before. There 
> should
> > be no changes for rerunning IDs on miniAOD.
> >
> > I meant tau discriminators run on top on pat::Taus, namely
> RecoTauTag/RecoTau/plugins/PPATTauDiscriminantCutMultiplexer.cc,
> ATTauDiscriminationByMVAIsolationRun2.cc,
> PATTauDiscriminationAgainstElectronMVA6.cc
These modules are currently not affected by the changes. I understood 
the original target (of course it can be extended :) ) to refactor the 
discriminator format produced during the reco step and saved in AOD, 
i.e. PFTauDiscriminator. When running the ID on PAT::Taus, 
PATTauDiscriminator objects are created, which I didn't create a 
'container' version of. I think this dataformat is just for runtime use 
and not saved in any files (correct me if I'm wrong). Therefore, I'm not 
sure whether we want to change it, too, unless we would change the 
PAT:Tau content. Does this answer your question better?

**Comment by mbluj** [comment]
Yes, it does answer. It can be that I miss something, I think that goals of the changes in this PR are
a) to reduce CPU/memory usage thanks to reducing number of executions of the sample plugin just to apply different cuts (defining WPs) on an output variable (Raw MVA),
b) to simplify configuration of tau sequences (smaller number of modules to configure).
c) to rationalize way in which discriminants are stored (and then handled) - one object instead of many, Boolean values instead of Double/Float ones, etc.
In my opinion a) and b) apply to pat::Tau-based discriminats as for reco::PFTau-based ones. In addition, a) and b) can be achieved even w/o a new dataformat - the discriminant modules can easy produce a set of products (of same format as currently) corresponding with a RAW discriminant(s) and WPs.  Is c) really an important goal (I know that it is said the main motivation of this PR)?

**Comment by swozniewski** [comment]
Right, these are the essential points, I think. I'm not quite sure about the 'ranking'. I thought the expected gain concerning a) would be rather small. Maybe Jan can comment on this better. In any case, I would appreciate a review on this part, so I know whether the way it has been realized so far is ok for you. Afterwards and when you have an impression on how the configs change, we should conclude where else to apply this.

**Comment by mbluj** [comment]
Just concerning the "ranking" - the points in my message are not ranked :) 
What concerns a): I have not measured usage of CPU/memory by tau modules, but at least naively there can be a gain if the module is loaded one time instead of 3-7 times (number corresponds with no. of WPs). The algorithms are not very CPU intensive, but modules itself reserve some amount of memory and usually handles big collections (e.g. PFlow cands.) which is probably costfull.  
Finally, we can certainty discuss the development with Jan (and other interested parties) to converge on some development model. Personally, I would start from modules producing Raw discriminants and related WPs in one go, but using current dataformat. It is to not change too much outputs and thus following modules. Then, I would add a new dataformat (as you propose). It can be done in one or even two PRs to official CMSSW. What do you think? 
Anyway, what is target release series for those changes? I'm asking to define timescale. CMSSW_10_3_0 is planned for the beginning of October, so there is less than one month if the development targets it, while 10_4_0 is expected for end of 2018.

**Comment by swozniewski** [comment]
> Just concerning the "ranking" - the points in my message are not ranked :)
> What concerns a): I have not measured usage of CPU/memory by tau 
> modules, but at least naively there can be a gain if the module is 
> loaded one time instead of 3-7 times (number corresponds with no. of 
> WPs). The algorithms are not very CPU intensive, but modules itself 
> reserve some amount of memory and usually handles big collections 
> (e.g. PFlow cands.) which is probably costfull.
> Finally, we can certainty discuss the development with Jan (and other 
> interested parties) to converge on some development model. Personally, 
> I would start from modules producing Raw discriminants and related WPs 
> in one go, but using current dataformat. It is to not change too much 
> outputs and thus following modules. Then, I would add a new dataformat 
> (as you propose). It can be done in one or even two PRs to official 
> CMSSW. What do you think?
>
Given the current status, I'm not convinced of this intermediate step: 
On one hand, in this pull request the new data format is already 
installed for the MVA IDs at reco level and their processing to pat taus 
and I think this could be easily transferred to the other modules. On 
the other hand, the TauDiscriminationProcucerBase 
(https://github.com/cms-sw/cmssw/blob/02d4198c0b6615287fd88e9a8ff650aea994412e/RecoTauTag/RecoTau/src/TauDiscriminationProducerBase.cc) 
is currently written to produce one dataformat (double before, with this 
pull-request also other types). We would have to enable production of 
multiple outputs although we won't need it with the new dataformat in 
the end.
>
> Anyway, what is target release series for those changes? I'm asking to 
> define timescale. CMSSW_10_3_0 is planned for the beginning of 
> October, so there is less than one month if the development targets 
> it, while 10_4_0 is expected for end of 2018.
>
I think it was rather 10_3_0 than 10_4_0 even though there was no 
specific deadline set. In principle, the current changes work. Depending 
on what changes you wish, I could be in time for that and at least this 
part could be migrated. If the changes already done are fine and I can 
apply it analogously to the remaining discriminators and/or the 
discrimination at PAT level, this could also run quite fast, I guess, 
and be ready for 10_3_0.

**Comment by steggema** [comment]
Concerning Michal's points a), b), c): I think it is important to roll back the proliferation of products we have in RECO/AOD, i.e. to reduce the number of products, and hence that c) is important, as stated by Sebastian. Similarly, b) is also an important goal, whereas a) is a nice side effect, in my opinion. 

My major comment on the implementation is whether we are happy with the vector of bools. An alternative would be to have a bitmap, like in NanoAOD, which would reduce the storage need.

**Comment by mbluj** [comment]
I think that bitmap, i.e. uint used as a bit map is a nice solution. However, one should store in some way a number of meaningful bits / WPs which gives an additional uint. On the other hand, I propose to replace float (for a raw discriminant) by a vector of floats to make the format more flexible - sometimes it can be useful to store some of them, e.g. for isolation sums where we have three (four) items: charged, neutral, PU (+combined) sums. I think the flexibility is worth some overhead.
I also propose modify the pat::Tau dataformat, conversion form Boolean WPs (regardless they are bits inside unit or variables of bool type) to floats, which are then stored, is not very nice. BTW, electron-Ids are also stored as floats in pat::Electron even if most of them are actually Booleans. 
Finally, cut-based discriminant should be also migrated to the new format which requires some effort, i.e. a new plugin (or a deep modification of current one) is needed. It could be that it is beyond of scope of this PR, but for me it is logical extension of it.

**Comment by steggema** [comment]
I agree that it would be nice to improve also the pat::Tau data format, and I can see this as part of this PR or as a separate one. It can make sense to have it within this one to make things fully consistent. It will require some additional thinking, in particular of the user interface, but it should be worth the effort.

**Comment by swozniewski** [comment]
Please note that std::vector<bool> is already optimized to use one bit per entry (https://en.cppreference.com/w/cpp/container/vector_bool), so it probably does not consume more storage than a bitmap, but is easier to handle.
Concerning a vector of floats instead of one raw value, this would also allow to have the category of the AntiElectronMVA in the container object.
As we start thinking about changing the PAT::Tau format, too, I guess these changes won't meet the migration of CMSSW_10_3_X. I tend to prefer one later, large pull request which would probably be more consistent as Jan said.
One general question: Should all PFTauDiscriminator and PATTauDiscriminator objects be replaced by the container format, so we would finally remove them from the code? Concerning CaloTaus, there's currently some other developments running (if I recall correctly what you mentioned once, Jan), so these we won't touch at the moment?

**Comment by mbluj** [comment]
> Please note that std::vector is already optimized to use one bit per entry
> (https://en.cppreference.com/w/cpp/container/vector_bool), so it probably
> does not consume more storage than a bitmap, but is easier to handle.
>
OK, makes sense. The only issue is that WPs (or different raw values) are
only numbered, i.e. any name is associated to them, so there is not a way
to distinguish between them in any human friendly way. But, I think it is
fine as long as some convention is respected, e.g. that WPs are included
from looses to the tightest. Problem occurs only when a new WP is added and
it is not tighter than previously defined... BTW, the same is true for
bitmaps. The only solution I can think about is to add a vector of names or
use maps instead of vectors, but both are not cost-less in terms of size.


> Concerning a vector of floats instead of one raw value, this would also
> allow to have the category of the AntiElectronMVA in the container object.
> As we start thinking about changing the PAT::Tau format, too, I guess
> these changes won't meet the migration of CMSSW_10_3_X. I tend to prefer
> one later, large pull request which would probably be more consistent as
> Jan said.
>
I also agree that it makes sense. In my opinion there is not rush as I
expect that it will be 10_4_X which will be used for final rereco. Deadline
for 10_4_0 is about end of the year, but of course it is better to have the
development sooner as its review can take some time.

> One general question: Should all PFTauDiscriminator and
> PATTauDiscriminator objects be replaced by the container format, so we
> would finally remove them from the code? Concerning CaloTaus, there's
> currently some other developments running (if I recall correctly what you
> mentioned once, Jan), so these we won't touch at the moment?
>
PFTau/PATTauDiscriminator is basically simple association map between
PFTau/PATTauRefProd and vector<float>, so the new dataformat will be a
straight extension of it where vector<float> will be replaced by the new
structure which will consists of vector<float> and vector<bool> or similar.
However, it can be easier firstly introduce the a new dataformat for
discriminator and new compatible plugins and then remove old ones with
other PR. In that way, this development will not couple with HLT which will
also require migration. Other possibility will be adjustment of current
plugins to the new dataformat which should be doable as the new dataformat
a simple extension of the current dataformat. This should be transparent
for HLT and backward compatible configuration-wise. In addition, in this
way unnecessary entities (dataformats) are not multiplied. But, it will
require some work on discriminants. Personally, I tend to prefer the second
option, i.e. update of dataformat and plugins.

Concerning storing tau-Ids in PATTaus: currently they are stored as a
vector of string-float pairs, where string is name of a discriminant and
float is its value. To get value of given discriminant the "tauID" method
iterates over the pair vector as long as discriminant name is found and
then returns the value. In case when the name is not found an exception is
thrown. This can be extended by adding a vector of string-bool pairs and
modifying the return method in the way that it firstly iterates over one
vector than another. It means that bool will be cast to float at retun, but
I think it is not a big problem. It can be also sensible to replace vectors
of pairs by maps (<string,float/bool>).

**Comment by swozniewski** [comment]
Jan and me had also thought about the problem of labeling the working points. We concluded that it is enough to have the definition in the reco configs. (The PAT config imports the reco config to find the correct indices.) It's of course not ideal as changes might lead to incompatibilities between file versions. So new WPs should better be just appended such that the meaning of the old indices stays the same. But saving a string (in a map or separate vector) in every single events is a large overhead. In the PAT-format the situation is a bit different, I think, because this should probably be more user friendly as more people who are not that much involved in the tau pog are using it. I like Michal's suggestions for the PAT format.
Concerning the update strategy I would be fine with both options.

**Comment by mbluj** [comment]
OK, I think we are all on the same page, so you can proceed. Namely
1. No labeling for AOD dataformat
2. Please extend current  `PFTau/PATTauDiscriminator` dataformat by adding to it `vector<bool>` for WPs and then adapt current producers to it. I mean adapt the ones which are not going to be fully moved to new dataformat, i.e. cut-based iso and anti-mu ones. Concerning MVAIso/anit-e: makes it sense to keep current producers at least for a while and in parallel prepare new ones for raw values and WPs? Please decide what is better for testing.
3. Extend pat::taus to handle the new dataformat. 
Anyway, the modifications are quite big so I think they should be discussed at a RECO meeting when well advanced, but before PR'ed.

**Comment by steggema** [comment]
On 13 Sep 2018, at 12:39, mbluj <notifications@github.com> wrote:
> 
> > Please note that std::vector is already optimized to use one bit per entry
> > (https://en.cppreference.com/w/cpp/container/vector_bool), so it probably
> > does not consume more storage than a bitmap, but is easier to handle.
> >
> OK, makes sense. The only issue is that WPs (or different raw values) are
> only numbered, i.e. any name is associated to them, so there is not a way
> to distinguish between them in any human friendly way. But, I think it is
> fine as long as some convention is respected, e.g. that WPs are included
> from looses to the tightest. Problem occurs only when a new WP is added and
> it is not tighter than previously defined... BTW, the same is true for
> bitmaps. The only solution I can think about is to add a vector of names or
> use maps instead of vectors, but both are not cost-less in terms of size.

Just because it's space-efficient in memory doesn't necessarily mean it's storage-efficient for ROOT output. I don't know though to which extent we should care about RECO/AOD output. Maybe something that can be asked to RECO.

**Comment by steggema** [comment]
@swozniewski Does #129 supersede this PR so it can be closed?

**Comment by swozniewski** [comment]
I just left it open because of our discussion here. But it's actually still accessible if the PR is closed, so I close it now.

**Pull request closed without merging**
