### PR TITLE
temporary HLT customization

### PR DESCRIPTION
**Pull request by swozniewski**

### CODE REVIEW

**Comment by mbluj** [comment]
Hi,
are you sure that this is the only type of modules which has to be customized? Have you tried run HLT with CMSSW including the "if(pset.exists)" cleaning?

**Comment by swozniewski** [comment]
@mbluj RecoTauJetRegionProducer was at least the only type mentioned in the error log of the three failed tests. Can you tell me how to run the HLT?

**Comment by mbluj** [comment]
> @mbluj <https://github.com/mbluj> RecoTauJetRegionProducer was at least
> the only type mentioned in the error log of the three failed tests. Can you
> tell me how to run the HLT?
>
It is correct, but I'm afraid that only 1st error is reported and then
process fails. So, one should try to run full HLT fix errors one by one and
then prepare the customization.
Concerning the recipe to run HLT, please execute the following commands in the setup CMSSW area:
```
$> hltGetConfiguration /dev/CMSSW_10_1_0/GRun --full --offline --mc --unprescale --process TEST --globaltag auto:run2_mc_GRun --no-output --max-events -1 --input /store/relval/CMSSW_10_3_0_pre3/RelValTTbar_13/GEN-SIM-DIGI-RAW/PU25ns_103X_upgrade2018_realistic_v4-v2/20000/0C6DACEB-1DD1-9E49-B3CF-0A5EBF845DB9.root > hlt.py
$> cmsRun hlt.py >& out_hlt.log &
$> tail -f out_hlt.log
```
I have tested this with plain CMSSW_10_3_0_pre4 at lxplus. The input file consists of 500 ttbar events which should be enough to run most of HLT triggers including tau ones. But of course you can use other file or more files - you just need edit hlt.py which is standard CMSSW configuration.

**Comment by mbluj** [comment]
To run hlt with the "if(pset.exists)" cleaning I had to use much more complex customization function. You can find it in `/afs/cern.ch/user/m/mbluj/public/customiseFor24501_fragment.py`
When the "if(pset.exists)" cleaning PR is accepted HLT guys will need update ConfDB and our trigger colleagues fix tau trigger paths where needed accordingly to the customization function.

**Comment by swozniewski** [comment]
@mbluj Thank you for already completing this! Should I check something else or just migrate your customization function?

**Comment by mbluj** [comment]
I think that you should also add `verbosity = cms.int32(0)` to `_shrinkingConeRecoTausConfig` and `_fixedConeRecoTausConfig` PSets in `RecoTauTag/RecoTau/python/RecoTauShrinkingConeProducer_cfi.py` and `RecoTauTag/RecoTau/python/RecoTauFixedConeProducer_cfi.py`, respectively.

**Pull request closed without merging**
