### PR TITLE
L2 tau identification with a CNN

### PR DESCRIPTION
**Pull request by valeriadamante**
In this PR the implementation of a machine learning based approach for the L2 taus is introduced. The chosen ML algorithm is a CNN trained with different hadronic taus production mechanisms (and reweighed in order to avoid overtraining for specific production mechanisms) versus fake taus coming from QCD. 

You can find: 
- the L2TauNNTagProducer which produces the CNN outputs for given L1Tau collections (>=1 collection). For each collection a vector of CNN output is created;
- the L2TauNNTagFilter which takes in input a L1 collection (just 1 in this case), the vector of CNN outputs and the CNN threshold. For the threshold, three different Working Points have been defines in order reach three different desired rate values (3kHz, 4kHz and 5kHz) - evaluated on  EphemeralHLTPhysicsX. For more information see the presentation at the TSG meeting [1]
- The L2TauML production file and a custom function (testL2TauTag) that includes the L2TauTagProducer+Filter 
- instruction on how to run the test in a README.md file

The trained CNN and the normalization file (needed to normalize the matrix which will be given in input to the CNN) is currently in my fork of the RecoTauTag-TrainingFiles repository as you can see from the instructions in the md file. 

[1] https://indico.cern.ch/event/1040952/contributions/4401915/attachments/2260841/3837378/L2TauIDCNN.pdf

### CODE REVIEW

**Comment by azotz** [comment]
Hi @valeriadamante 
The instructions inside the README.md do not work for me properly. Using `hltGetConfiguration` with the given command [here](https://github.com/valeriadamante/cmssw/blob/L2TauTagNN/RecoTauTag/HLTProducers/test/README.md#l2taunntag-test) gives me an error. The command seems to be incomplete as it is missing the positional argument `/path/to/configuration`. Can you provide a working command?

Following [https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideGlobalHLT](https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideGlobalHLT), I can produce a `HLT_User_cff.py`, but then running the test crashes with
```
AttributeError: 'Process' object has no attribute 'HLTGlobalPFTauHPSSequence'
```
Is this, what is mentioned in the README? It is not clear to me how this can be fixed

**Comment by valeriadamante** [comment]
Hi @azotz 
Unfortunately at this iteration I had to put manually the ```HLTGlobalPFTauHPSSequence``` into ```HLT_User_cff.py``` as it's written into the README.md file. This means copying from the ```HLT_GRun_cff.py``` file all the needed paths/sequences to include the  ```HLTGlobalPFTauHPSSequence``` one to the ```HLT_User_cff.py``` file. If you do not manage to include all of them I can send you in private my  ```HLT_User_cff.py``` file. I hope I was clear but if you have still some issues please let me know

**Comment by valeriadamante** [comment]
Hi @azotz 
I realised that the ```hltGetConfiguration``` command was wrong and I fixed it, including a path that contains the HLTGlobalPFTauSequence so that it's no more necessary to include it by hand. Now instructions should be simpler and more correct. Let me know if you still have problems!

**Comment by azotz** [comment]
The master branch of `RecoTauTag/TrainingFiles` is checked out when following the instructions, but the relevant training files are located in the `L2Taus` branch, I assume. You can specify the branch in the clone command with `-b <branch_name>`

**Comment by azotz** [comment]
Running with the described changes gives me the following error message now:
```
An exception of category 'Configuration' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=DTRecHitProducer label='hltDt1DRecHits'
Exception Message:
MissingParameter: Parameter 'readLegacyTTrigDB' not found.
```

**Comment by valeriadamante** [comment]
Hi @azotz 
I fixed all the errors and I tested it. Now everything should work with the whole menù. Please let me know if there is some other problem.

**Comment by valeriadamante** [comment]
Hi @azotz 
I realised I forgot to add a function in testL2TauTagNN.py 
If you want I can add it otherwise if it's simpler you can add it before merging to the central repo. It should be put under this function (at L 51) https://github.com/cms-tau-pog/cmssw/blob/8a35e17bd50e2516e4e3a8244067b46b554859ad/RecoTauTag/HLTProducers/test/testL2TauTagNN.py#L46-L51  
```
def addFilesToList(fileList, inputFiles, fileNamePrefix):
    """read intput file list from a another list"""
    for name in inputFiles:
        if len(name) > 0 and name[0] != '#':
            fileList.append(fileNamePrefix + name)
```

**Comment by azotz** [comment]
I can add it

**Pull request merged**
