### PR TITLE
DNN tau IDs for CMSSW_10_4_X

### PR DESCRIPTION
**Pull request by MRD2F**
Forward-porting DNN-related developments (#98, #99, #101)  to CMSSW_10_4_X.

### CODE REVIEW

**Comment by mbluj** [comment]
Hello,
this is pull request (PR) to an incorrect branch: you should prepare a PR to `cms-tau-pog:CMSSW_10_4_X_tau_pog_DNNTauIDs` rather than to `cms-tau-pog:CMSSW_10_0_X_tau-pog`. Therefore, I am closing this PR.
P.S. Please prepare a brief description of your next PR as it is useful recording of work done. Thanks.

**Comment by kandrosov** [comment]
@mbluj why to open a new PR? @MRD2F fixed the target branch (see above).

**Comment by mbluj** [comment]
On Wed, Oct 24, 2018 at 6:03 PM Konstantin Androsov <
notifications@github.com> wrote:

> @mbluj <https://github.com/mbluj> why to open a new PR? @MRD2F
> <https://github.com/MRD2F> fixed the target branch (see above).
>
Not sure is I understand the issue, but try to answer:
1. Open your development branch with a web browser: `
https://github.com/MRD2F/cmssw/tree/CMSSW_10_4_X_DPFIsoDeepTau`
2. Click on "Pull request" on the right
3. Choose target as "cms-tau-pog" and "CMSSW_10_4_X_tau_pog_DNNTauIDs" with
buttons on the left
4. Create a (new) PR.

Does it answer your question?

**Comment by mbluj** [comment]
Target branch was updated which was overlooked => the PR is reopened

**Comment by mbluj** [comment]
Tested: results as for 94X version with the same (94X) inputs modulo small migrations at intermediate values of DPF v0 and v1 score probably due to a bit different packing inside packedCandidates (puppi weights?). The differences are expected to not affect current Tight WP by Owen (and other sensibly tight WPs).

**Comment by mbluj** [comment]
@MRD2F @kandrosov now you can prepare version for 102X, please.

**Comment by MRD2F** [comment]
> @MRD2F @kandrosov now you can prepare version for 102X, please.

ok, I'll start with that

**Pull request merged**
