### PR TITLE
fix for phitAtEcalEntrance variable

### PR DESCRIPTION
**Pull request by alebihan**

### CODE REVIEW

**Comment by mbluj** [comment]
Hi A-C,
thank you for the fix. However I have a few comments:
1. Will it be possible to have a switch to desired behaviour when phiAtECalEntrance is read from patTau? It is not filled in the current implementation in 80X, but it exits? Please correct me if I remember it wrong
2. I think it would be better to have the atECalEntrance method with the 'part' argument being reference to reco::Candidate which a base class for both pat::PackedCandidate and reco::PFCandidate than two overloaded methods. The method does not use any specific methods of the classes, so I think implementation with reco::Candidate is more elegant.
3. Do we want to port it also to 81X and newer for keeping compatibility (cf. 1.) or it should be treat as a temporary fix?

Michał

**Comment by alebihan** [comment]
Hi Michal,
Thanks for your comments. Here the answers from my point of view.
1. Not fully sure to understand your comment, the phiAtecalEntrance variable has been changed for both MVA computations, for AODs and miniAODs. I' haven't changed the code to access the new training from the database yet.
2. thanks ! I've fixed it, only in my area so far (https://github.com/alebihan/cmssw/blob/CMSSW_8_0_X_tau-pog_miniAOD-backport-tauID_AC_PR/RecoTauTag/RecoTau/src/AntiElectronIDMVA6.cc), I can initiate a new PR, if Roger and you agree.
3. Do we foresee a new training for 81 or not ? if not then we should probably fix 81 as well.
Cheers,

AC

**Comment by mbluj** [comment]
Hi AC,

0. My comment 1. was about possible switch between phiAtecalEntrance computed with AOD ('standard method') and computed at MiniAOD ('recovery method')
1. You do not need a new PR if you modified your branch at github - your commit is seen in the original PR
2. We will need a new training for 2017 due to changes in tracking which follow upgraded detector - 4th pixel layer. Probably we will need more than one training as tracking in 81X is not final one, it is also expected tuning of GSF which for sure will impact the e/tau discrimination.

Michal

**Comment by alebihan** [comment]
Hi Michal,

0. Right now all methods should give similar results at AOD and miniAOD level. Would you like to keep the original method for AODs ? Or allow to roll back for both AODs and miniAODs to the original phiAtEcalEntrance computation ?
1. ok, good !
2. I would say it's probably easier to have the same code in both branches (?) Even if we retrain with the original phiAtEcalEntrance value.

Cheers,

AC

**Comment by mbluj** [comment]
Hi,

cf 0. Original method should in principle give different results than new one for gsfTracks where momentum in vertex is different than in the outermost point, while it should be (almost) irrelevant for KF tracks. So, it can differentiate between the two and I will keep the original method for further checks. However, your studies show that the difference between the new and old methods is negligible.
cf 2. I agree, it is better to have same code in both branches. 

M.

**Comment by alebihan** [comment]
Hi Michal,

Would a flag help ? Added to the 2 MVAValue() methods dealing with AOD objects ?

MVAValue(const reco::PFTau& thePFTau,
				    const reco::GsfElectron& theGsfEle, bool usefixPhiAtEcalEntrance)
and
MVAValue(const reco::PFTau& thePFTau, bool usefixPhiAtEcalEntrance)

The old variable can't be recomputed from miniAODs. At least for 80X. I could provide a switch  for 81X for miniAODs, but then we would have two versions.

Cheers,

AC

**Comment by mbluj** [comment]
Hi

Yes, I think flag is what we need.
MiniAOD: yes, I know that old variable cannot be recomputed with MiniAOD, but here the flag can switch between the old from a pat::tau computed at AOD (not accessible in 80X) and the recomputed one. Does it makes sense? In 80X switch to the one from  pat::Tau should return a warning that the switch is not possible (when an object is constructed). It will of course introduce a difference, but I think it should not be a problem when clearly implemented. 
@roger-wolf, what do you think?

M.

**Comment by alebihan** [comment]
Hi, 
I've committed a new version with flags for the AOD methods. For miniAODs the switch is implemented as well but the code will only compile for 81,  not for 80 as the method phiAtEcalEntrance() doesn't exist for miniAODs. How can I make it 80 compliant  ?

Cheers,

AC

**Comment by roger-wolf** [comment]
Hi Michal,

yes I agree that this is one way how things could be done.

Cheers,
Roger

**Comment by roger-wolf** [comment]
Hi A.-C.,

your commit looks incomplete to me. What I would expect is that the 
decision be taken on the cfi level. I see the boolean in the plugin but 
not in any cfi? I might miss something here.

In general one would give the possibility to decide on the cfi level. 
The plugin then reads out the boolean from the cfi and follows the 
decision to calculate phiAtEcalEntrance either on the fly or to take it 
from a precalc'ed place. In 81X just one or the other is done based on the decision. In 80X 
where the pre-calculated value is not available you add a EDM exception or a warning
with a statement that this option is not available for this release and 
either stop the program or switch to the calculation on the fly, 
whatever you think is more appropriate.

This means that in 81X and 80X you have two differing versions of the 
plugin implementation. This is what michal also had in mind, I think.

Cheers,
Roger

NB: I'll open a 81X branch for asa I get to it during the week.

**Comment by mbluj** [comment]
I confirm that I have in mind what Roger explained in a more clear way than I have done :)

**Comment by alebihan** [comment]
Thanks, totally clear now,  was missing the idea of the different plugins !

I tried to prepare this for 80. For 81 I would only have to remove the exception in the beginEvent() of PATauDiscriminationAgainstEelctronMVA6. 

Cheers, AC

**Comment by mbluj** [comment]
Hi,

I went via your code and it looks quite fine after this quick inspection (I leave more detailed view to Roger). The only thing I spot is the fact that the exception is thrown by the beginEvent() method - I think it should be moved to the beginJob() method or to the constructor as the wrong flag is a general logical problem rather than an event specific issue. Do you agree? 

M.

**Comment by alebihan** [comment]
Hi,
yep, makes sense, I moved it to the constructor now. 
AC

**Pull request merged**
