### PR TITLE
add low pt tau collection

### PR DESCRIPTION
**Pull request by gitytakahas**
add low pt tau collection codes based on PF-level

### CODE REVIEW

**Comment by steggema** [comment]
Hi all,
I created a topic branch for Yuta's low pT tau development. There is no immediate goal to get this into CMSSW, but this is rather meant for other people to be able to run this as well. I suppose some code checks will still be useful.
@roger-wolf @rmanzoni @swozniewski @mbluj

**Review by steggema — CHANGES_REQUESTED** [review]
Submodules in CMSSW should always be uppercase (lowPtTau ->LowPtTau)

Apart from that, I'd rather add this to  DataFormats/Tau

**Comment by steggema** [comment]
OK, from further looking at the code, it seems that it is very very far away from being deployable in CMSSW. If the goal is really to have this only available to users in a dedicated branch, we can probably live with lower quality requirements (and we'll anyway have to rebase/squash for central deployment). We can discuss this in the next regular meeting.

**Comment by gitytakahas** [comment]
Yes, I know it is very far away from merging this into CMSSW. Please consider this as experimental.

**Comment by steggema** [comment]
Ok, let's proceed as follows: I merge this so we have a baseline, but for any proper integration, we'll need a review and a rebase of the developments.

**Pull request merged**
