### PR TITLE
forward-porting DNN-related from branch cms-tau-pog:CMSSW_9_4_X_tau_pog_DNNTauIDs

### PR DESCRIPTION
**Pull request by MRD2F**
Changes regarding forward-porting DNN-related developments from the PRs #105 and #106 from 94X to 104X

Memory tests were performed and they're attached here. The results are consistent with the ones obtained with the 94X release ( #105) .

[memory_usage_.pdf](https://github.com/cms-tau-pog/cmssw/files/2592376/memory_usage_.pdf)

### CODE REVIEW

**Comment by MRD2F** [comment]
One comment I forgot to mention before, the sample that I used for the test was:  
/store/mc/RunIIFall18MiniAOD/TTToHadronic_TuneCP5_13TeV-powheg-pythia8/MINIAODSIM/102X_upgrade2018_realistic_v12-v1/100000/4A357FA9-ACD1-A546-956F-C0017C2CCD6D.root ,

with globaltag: 103X_upgrade2018_realistic_v8, and runned with 100 events. Also the files with more information for DeepTau, DPFv0 and DeepTau+DPFv0 I'm putting them here.
 

[igprof-analyse-DeepTau_quantized.txt.gz](https://github.com/cms-tau-pog/cmssw/files/2594457/igprof-analyse-DeepTau_quantized.txt.gz)
[igprof-analyse-DeepTauPlusDPFv0_quantized.txt.gz](https://github.com/cms-tau-pog/cmssw/files/2594458/igprof-analyse-DeepTauPlusDPFv0_quantized.txt.gz)
[igprof-analyse-DPFv0_quantized.txt.gz](https://github.com/cms-tau-pog/cmssw/files/2594459/igprof-analyse-DPFv0_quantized.txt.gz)

With the same configuration than before, I also preformed CPU use test, with the original and quantized files, for: DeepTau, DPFv0 and DeepTau with DPFv0 . The file with the summarized information about the CPU time of the method ' deep_tau::DeepTauBase::produce' is in here 
[CPU_use.pdf](https://github.com/cms-tau-pog/cmssw/files/2595032/CPU_use.pdf). The files with the complete information are these:

[DeepTauCPU.txt.gz](https://github.com/cms-tau-pog/cmssw/files/2595042/DeepTauCPU.txt.gz)
[DeepTauOriginalCPU.txt.gz](https://github.com/cms-tau-pog/cmssw/files/2595043/DeepTauOriginalCPU.txt.gz)
[DeepTauPlusDPFv0CPU.txt.gz](https://github.com/cms-tau-pog/cmssw/files/2595044/DeepTauPlusDPFv0CPU.txt.gz)
[DeepTauPlusDPFv0OriginalCPU.txt.gz](https://github.com/cms-tau-pog/cmssw/files/2595045/DeepTauPlusDPFv0OriginalCPU.txt.gz)
[DPFv0CPU.txt.gz](https://github.com/cms-tau-pog/cmssw/files/2595046/DPFv0CPU.txt.gz)
[DPFv0OriginalCPU.txt.gz](https://github.com/cms-tau-pog/cmssw/files/2595047/DPFv0OriginalCPU.txt.gz)

**Comment by mbluj** [comment]
Thank you! I'll take a look today or a few next days.

**Comment by MRD2F** [comment]
I preformed the CPU use tests again, but this time with 1000 events, to see if the difference in time of the original files and the quantized decreased, and indeed happen, as it can be seen in here: 
[CPU_use_1000events.pdf](https://github.com/cms-tau-pog/cmssw/files/2595335/CPU_use_1000events.pdf). 

The sample I used for this test was: /store/mc/RunIIFall18MiniAOD/TTToHadronic_TuneCP5_13TeV-powheg-pythia8/MINIAODSIM/102X_upgrade2018_realistic_v12-v1/100000/BFA43300-C42C-8442-91B7-23DAD4599D00.root

The files with the complete information, as it was said in the comment before, are these:

[DeepTauCPU.txt.gz](https://github.com/cms-tau-pog/cmssw/files/2595341/DeepTauCPU.txt.gz)
[DeepTauOriginalCPU.txt.gz](https://github.com/cms-tau-pog/cmssw/files/2595342/DeepTauOriginalCPU.txt.gz)
[DeepTauPlusDPFv0CPU.txt.gz](https://github.com/cms-tau-pog/cmssw/files/2595343/DeepTauPlusDPFv0CPU.txt.gz)
[DeepTauPlusDPFv0OriginalCPU.txt.gz](https://github.com/cms-tau-pog/cmssw/files/2595344/DeepTauPlusDPFv0OriginalCPU.txt.gz)
[DPFv0CPU.txt.gz](https://github.com/cms-tau-pog/cmssw/files/2595345/DPFv0CPU.txt.gz)
[DPFv0OriginalCPU.txt.gz](https://github.com/cms-tau-pog/cmssw/files/2595346/DPFv0OriginalCPU.txt.gz)

**Comment by mbluj** [comment]
Tested, results as with 94X version.

**Pull request merged**
