### PR TITLE
Tau reco&Id on top of MiniAOD (94X)

### PR DESCRIPTION
**Pull request by mbluj**
As title says. it is PR for Tau reco&Id on top of MiniAOD. 
* It ports code by Jan (@steggema) to 94X
* On top of the port it consists of the following fixes and improvements
   * Fix avoiding some (rare) crashes when run with RECO/AOD due to lack of track (showing up in boosted tau reco),
   * Fixed and improved filtering of pat::PackedCandidates => better reproduction of isolation Pt-sums at MiniAOD
   * Tau PV and SV producers for MiniAOD with refits => improved reproduction of tau time-life related variables,
  * A new plugin recovering charged hadrons from tracks not considered by PFlow using 'lostTracks' collection – related to reconstruction of new decay modes (overall a marginal change),
  * A new against-muon discriminant for MiniAOD, 
  * A new tool to adapt standard configuration to be run at MiniAOD with example cfg configuration file. It includes for instance a tau seeding with raw AK4Jets as in RECO/AOD

Some details on performance of the new code on AOD and MiniAOD can be found in slides here [1].

@roger-wolf: could you please perform your standard tests and then merge [2][3]? 

@steggema, @roger-wolf: I would like to start to proceed towards integration with official CMSSW. To do so I would like we agree the following:
* Who can port it to 10_0_X: Roger or myself?
* Should we present it to MiniAOD people already now or when we have port to 10_0_X?
* Should we ask MiniAOD people to add some extra info for against-muon veto already now, or wait with it? If we ask what will be the best strategy in your opinion: do we want to extend cases (from isolated charged hadrons to all charged candidates) when already present data member of PackedCandidas is filled (uint8_t rawCaloFraction_) or we ask for a new datamember (uint8). The former will not require change of the data format, while the latter will be more similar to what we are doing at RECO/AOD.
* Finally, who can take care on the integration? I expect a number of comments as the new code consists a lot of changes, sometimes "reducing" quality of the code, like conversions from edm:Ptr/edm:Ref to C++ pointer/reference. It is done in a purpose (to deal with tracks and pseudoTracks from PackedCandidates in the same way), and I think safely, but it will for sure be closely scrutinized.

@steggema, @roger-wolf: regardless on integration to official CMSSW:
* I think we should publish (put at a Tau POG TWiki) a recipe to use the current version when integrated to the tau-pog repo.
* I will be glad if it is tested by other people including you and your students.

---
[1] https://indico.cern.ch/event/682875/#2-updates-on-tau-reconstructio

[2] Probably it is trivial, but to checkout the code one need to the following on top of CMSSW_9_4_0:
* Checkout packages to be modified
git-cms-addpkg /DataFormats/PatCandidates /DataFormats/TauReco /PhysicsTools/PatAlgos  /RecoTauTag/RecoTau /RecoTauTag/Configuration
* Add my repository
git remote add modifiedRepo https://github.com/mbluj/cmssw.git
git fetch modifiedRepo
* Create a new branch and make it point to my repo
git checkout modifiedRepo:CMSSW_9_4_X_miniAOD-tauReco

[3] To run tau reco&id at RECO/AOD use standard sequences, for running at MiniAOD (only standard reco, i.e. not boosted) use RecoTauTag/Configuration/test/tauFromMiniAOD.py (should work on a computer with access to samples on grid via xrootd)

### CODE REVIEW

**Comment by roger-wolf** [comment]
Dear Michal,

thanx a lot for thi PR. I'll give a few answers/comments to questions 
raised by you below:


> @roger-wolf <https://github.com/roger-wolf>: could you please perform 
> your standard tests and then merge [2][3]? 

I will have a look to your changes and on the way can make an effort to 
port it to CMSSW_10_0_X. I'll start tomorrow (w/ a short break on 
Wed/Thur when I'll give a seminar in Bonn). I'll let you know how I 
proceed.


> @steggema <https://github.com/steggema>, @roger-wolf 
> <https://github.com/roger-wolf>: I would like to start to proceed 
> towards integration with official CMSSW. To do so I would like we 
> agree the following:
>
>   * Who can port it to 10_0_X: Roger or myself?
>

I can do it. Might be that come back to you with quesitons.


>   * Should we present it to MiniAOD people already now or when we have
>     port to 10_0_X?
>

Depending on how pressing it is I'd wait for the CMSSW_10_0_X 
integration first. This is also the preferred order by Slava & Co


>   * Should we ask MiniAOD people to add some extra info for
>     against-muon veto already now, or wait with it? If we ask what
>     will be the best strategy in your opinion: do we want to extend
>     cases (from isolated charged hadrons to all charged candidates)
>     when already present data member of PackedCandidas is filled
>     (uint8_t rawCaloFraction_) or we ask for a new datamember (uint8).
>     The former will not require change of the data format, while the
>     latter will be more similar to what we are doing at RECO/AOD.
>   * Finally, who can take care on the integration? I expect a number
>     of comments as the new code consists a lot of changes, sometimes
>     "reducing" quality of the code, like conversions from
>     edm:Ptr/edm:Ref to C++ pointer/reference. It is done in a purpose
>     (to deal with tracks and pseudoTracks from PackedCandidates in the
>     same way), and I think safely, but it will for sure be closely
>     scrutinized.
>

what you write makes sense to me. But indeed reads like triggering 
question by RECO. As long as it is purely technical questions I can 
safely take are of the baby sitting.

Cheers,
Roger

**Comment by mbluj** [comment]
Thank you Roger. I think it will make a lot of sense to meet with you and Jan before or just after the EoY HTT workshop and discuss an integration plan for taus@MiniAOD. I'm going to be at CERN between December 11th (around lunch time) until 15th (until about 5:30pm).

**Comment by steggema** [comment]
Sounds very good to me, I'll be around the full time.

**Comment by roger-wolf** [comment]
Hi Michal, 

I'll merge your work now into the tau-pog branch and have a closer look into what you did then from next week on. Once the HTT workshop starts I should have had the first look into it. The forward I'll try to do in one go. 

Cheers,
Roger

**Comment by roger-wolf** [comment]
Dear colleagues, 

I've just made an independent test of Michal's PR on a  ttbar relval sample based on which I've made my own comparisons (*) using the mini validation suite (**). I can confirm the following:
   * code compiles w/o problems 
   * tau-reconstruction based on miniAOD event content works out of the box
   * perfect agreement between tau reco based on AOD input and tau reco based on miniAOD input on the used relval file

I'll now run the typical matrix test since this is a PR with many changes in many lines of code it might be worth doing this. Then I'll prepare the PR. @mbluj @steggema does it make sense also to trigger a TauPOG internal round of RelVal?

As Michal says we should expect closer scrutiny since this is quite a significant number of changes in files and also some might not comply with CMS RECO rules. We can still just see how far this PR will carry us. Once settled I'll start the forward to CMSSW_10_0_X (unless forced otherwise by Slava et al). I'll do this the old fashioned way, line by line checking what is actually done and why... It might not harm to do it that way, but I anticipate that this will happen not this year any more.  

Cheers,
Roger

(*)  
[compareTauVariables.pdf](https://github.com/cms-tau-pog/cmssw/files/1567548/compareTauVariables.pdf)

(**)
https://twiki.cern.ch/twiki/bin/view/CMS/SWGuidePFTauIDDevelopers#Mini_s_w_validation_suite

**Comment by mbluj** [comment]
Hi Roger,

thank you for your checks.

* about validation: 
   * I think we should run matrix tests (at least reduced ones) as there are changes in the code run as part of reco sequences. The updated code should give exactly same results as current one, but it is better to check it with standard workflows.
  * I also think it will be useful to compare taus produced on top of MiniAOD (selectedPatTaus) with taus on top of AOD (slimmedTaus) as in my understending you compared new and original taus built on top of AOD, right?
* about integration to CMSSW: 
   * Jan (@steggema) mentioned at some point that he would like to restore original history of his commits which will help in the code revision process. So, I think you both should agree how to proceed. 
   * We should also check status of Alex Toldaiev's work on configuration cleaning as it obviously will interfere with these developments. 

Cheers,
Michał

**Comment by roger-wolf** [comment]
Hi all, 

I think restoring code history might not be necessary, but this is my personal opinion. To my experience Slava will anyhow go though the changes file by files.

**Comment by steggema** [comment]
How about I rebase my developments on top of 10X? This should save you some work, and I know the intentions better?

**Comment by roger-wolf** [comment]
Ok, let's do that.


Am 18.12.2017 um 13:25 schrieb Jan Steggemann:
> How about I rebase my developments on top of 10X? This should save you 
> some work, and I know the intentions better?
>

**Comment by steggema** [comment]
Here's my part of the development: https://github.com/steggema/cmssw/tree/TauRecoMiniAODRebased_10X
I'll also try to rebase Michal's part right now.

**Comment by steggema** [comment]
Here's a branch on which Michal's additional commits are also rebased: https://github.com/cms-sw/cmssw/compare/CMSSW_10_0_X...steggema:TauRecoMiniAODRebased_Michal_10X?expand=1

Michal, maybe it makes most sense if you test it given you have a working testing setup that you used for the 94X development?

**Comment by mbluj** [comment]
Yes, I can do the check. Should most recent 10_0_X prerelease (pre2) work or it is better to use an integration built? And do you know if 94X samples are still valid inputs?

**Comment by steggema** [comment]
I've made the setup with CMSSW_10_0_0_pre2, but it should cleanly merge into an integration build. I'm not sure we already need to move to an integration build since we'll probably not make an official PR before January (or so I think). I've added a commit that edits RecoTauTag/Configuration/test/tauFromMiniAOD.py adding CMSSW_10_0_0_pre2 relvals (and prevents an error due to missing VVLoose Old DM MVA Iso recalculation).

**Comment by roger-wolf** [comment]
Dear colleagues, 

I'm now ready to prepare the PR for 94X. Note that in preparation of this PR I needed to address some knock-on effects of templates in a bunch of plugins in the RecoTauTag/TauTagTools package (*). If you have the spare time you could address those in one go. 

Cheers,
Roger

(*)
	modified:   RecoTauTag/TauTagTools/plugins/PFTauViewRefSelector.cc
	modified:   RecoTauTag/TauTagTools/plugins/RecoTauDecayModeTruthMatchPlugin.cc
	modified:   RecoTauTag/TauTagTools/plugins/RecoTauDistanceFromTruthPlugin.cc
	modified:   RecoTauTag/TauTagTools/plugins/RecoTauObjectEmbedderPlugin.cc
	modified:   RecoTauTag/TauTagTools/plugins/RecoTauPiZeroFlattener.cc
	modified:   RecoTauTag/TauTagTools/plugins/RecoTauRandomCleanerPlugin.cc

rest seemd to be fine on matrix tests apart from DAS_ERORRS, which I have no control on.

**Comment by steggema** [comment]
It looks like the following commit was missed in the collated commit:

https://github.com/steggema/cmssw/commit/acf94664653cc8134bbe12c0b41d2f080b6d59f5

Things should be fine on the 10X branch:

https://github.com/steggema/cmssw/tree/TauRecoMiniAODRebased_Michal_10X

**Comment by mbluj** [comment]
Hello,

I have just got results of tests of the TauRecoMiniAODRebased_Michal_10X version. First at all, taus with template-based code on top on AOD are identical to those with original one. Then, taus reconstructed on top of MiniAOD show same differences wrt ones on top of AOD as it was observed with 94X, which is fine. The only a bit bigger difference is related to MVAIso, but now I compare 2017v1 training, while previously it was 2015 one. For me, it looks that the new training somehow stronger enhances differences between inputs than older one does. But, to understand the effect better one should inspect more carefully most important inputs (esp. no. of photons and shape variables) which I do not do (isolation sums and life-time info look fine).

**Comment by roger-wolf** [comment]
Dear colleagues, 

sorry, I was under the impression from our conversation that we wanted to have these developments integrated in 94X and this even, if possible, such that we can meet the 94X rereco/reminiAOD timelines. Otherwise we could have postponed the whole integration business to next year right away, no? Also the thoughts about doing a 94X integration before the 10X integration that were exchanged during the HTT workshop are obsolete. On the other hand it's true that once full tau RECO on miniAOD is possible we do not rely on such timelines anymore. 

Now since I have learned that I should not even have started the integration for 94X, and since, as anticipated, we contradict cmssw integration policies and will not be able to proceed with an integration of this PR even if we wanted, what do we do with the PR? 

I tend to keep it open, so that comments that Slava has made and fixes that should be applied can directly be taken into account for the 10X PR to come. In this way this work can still be useful for review even before the 10X integration is in place. 

Next question for me: how do we proceed beyond the integration of 10X. Should I close this PR after the 10X has been initiated or should we still pursue it for the good? Michal stated that it implies DataFormat changes, which would turn an integration impossible. But I think this has been halfway addressed by a comment and reply by/to Slava in the context of the PR. 

NB: 
It's unlikely that I will still do anything (but maybe addressing the CLANG error) this year. I'll be gone from this afternoon on. Yesterday I was blocked by an all day meeting that I had to attend. According to me it is fine just to restart the whole business after a small rest after the Christmas break (i.e. from mid of Jan on). But some clarification on how we would like to proceed might still be good and some time between now and Jan. 

Cheers,
Roger

**Pull request merged**
