### PR TITLE
Tau cluster variable refactoring: Avoid code duplication

### PR DESCRIPTION
**Pull request by steggema**
@mbluj @swozniewski This templates pt_weighted_dx to avoid code duplication. The only solution I could come up with introduces two template parameters, since pat::Tau and reco::PFTau return incompatible collections of (PF)Candidates. This may actually become easier to solve once the tau reco@MiniAOD PR is merged, but since the timescale of that PR is uncertain, we may go forward with this, or maybe a simplified version of it that you can come up with.

### CODE REVIEW

**Comment by mbluj** [comment]
I agree that this solution with double-templated code is a bit tricky and not sure if it really makes code easier to understand and maintain. In addition I'm not sure if it is worth implementation as solution with tau-reco@MiniAOD (hopefully close to be merged) will be nicer. We can back to this in case there are plans to backport this refactoring to older releases where backport of tau-reco@MiniAOD is not expected. Do you agree?

**Comment by steggema** [comment]
Yes, I agree. Let's keep it in mind as a future upgrade. I think it's generally good to try to get rid of some of the code duplication, but it may indeed be easier when we can consistently use Candidates. We can maybe leave this one open during the code review if Slava wants to see why addressing his comment leads to cumbersome changes.

**Comment by mbluj** [comment]
I agree.

**Comment by mbluj** [comment]
On the request of Reco coordinators (Slava) merging templated code to avoid duplications.

**Pull request merged**
