### PR TITLE
Adding HLTDoubleSinglet class and HLT3DoublePFTauPFJet filter

### PR DESCRIPTION
**Pull request by jaimeleonh**
This PR adds class HLTDoubleSinglet which, looking at three collections col1, col2 and col3, filters events where there are no objects in col3 unmatched with an object from col1 and another (different) object from col2. col1, col2 and col3 could be the same or different collections.

Using this class, a filter called HLT3DoublePFTauPFJet is defined using col1=col2=PFTau and col3=PFJet, so it can be used in a newly developed DoubleTau+Jet HLT path.

### CODE REVIEW

**Review by mbluj — CHANGES_REQUESTED** [review]
Hi @jaimeleonh,

Thank you for this development. For now I have only a set of comments on code "cosmetics"
* Should the class be called HLTDoubletSinglet rather than DoubleSinglet (missing "t" in "doublet")?
* please use standard code for deltaPhi and deltaR from here: https://github.com/cms-sw/cmssw/blob/master/DataFormats/Math/interface/deltaPhi.h deltaR. BTW, it is better to use deltaR2 (squared deltaR) instead of deltaR to avoid sqrt, same for mass (small but easy improvement of performance),
* please avoid variable names starting with capital letter, e.g. `I`, `Ip`, etc.,
* you can replace `unsigned int` by `size_type`,
* at the end please run `scram b code-format` which aligns formatting with CMSSW standars (spaces, line breaking, etc.)

**Comment by jaimeleonh** [comment]
Hi @mbluj , to be true, I don't really know what the t stands for. My first thought was "template", so I left it at the end, but I have no problem in adding the other t.

**Comment by mbluj** [comment]
> Hi @mbluj , to be true, I don't really know what the t stands for. My first thought was "template", so I left it at the end, but I have no problem in adding the other t.

"Doublet" is for a pair of objects, while "Singlet" for one object, so I suppose name should be DoubletSinglet for pair+one. However one can note that it is triplet from two pairs having one common element, (13) and (23). Template would be mentioned by capital T at the end of the name like DoubletSingletT

**Comment by mbluj** [comment]
@jaimeleonh I am reviewing your last commits right now, but for future it is better to use `git mv` to rename a file rather than copying and removing old one as the latter breaks history.

**Review by mbluj — APPROVED** [review]

**Comment by mbluj** [comment]
@jaimeleonh I approved your changes and I will merge your PR. But are you sure that you run `scram b code-format`? I see that it applied corrections in my checkout (which I will commit myself).

**Pull request merged**
